services:
  udemy.auth.api:
    image: ${DOCKER_REGISTRY-}udemyauthapi
    build:
      context: .
      dockerfile: Udemy.Auth/Udemy.Auth.API/Dockerfile
    environment:
      - POSTGRES_HOST=udemy.postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=udemydb
      - POSTGRES_USER=udemyuser
      - POSTGRES_PASSWORD=udemypassword
    depends_on:
      - udemy.postgres

  udemy.postgres:
    image: postgres:latest
    container_name: udemy_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: udemydb
      POSTGRES_USER: udemyuser
      POSTGRES_PASSWORD: udemypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - udemy.postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

