services:
  udemy.auth.api:
    image: ${DOCKER_REGISTRY-}udemyauthapi
    build:
      context: .
      dockerfile: Udemy.Auth/Udemy.Auth.API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - POSTGRES_HOST=udemy.postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=udemydb
      - POSTGRES_USER=udemyuser
      - POSTGRES_PASSWORD=udemypassword
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.auth.api
      - API_HTTP_PORT=5000
      - API_HTTPS_PORT=5001
    depends_on:
      - udemy.postgres
      - consul
    networks:
      - udemy_network

  udemy.apigateway.api:
    image: ${DOCKER_REGISTRY-}udemyapigatewayapi
    ports:
      - "3000:8080"
      - "3001:8081"
    build:
      context: .
      dockerfile: Udemy.APIGateway/Udemy.APIGateway.API/Dockerfile
    environment:
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.apigateway.api
      - API_HTTP_PORT=3000
      - API_HTTPS_PORT=3001
    networks:
      - udemy_network

  udemy.postgres:
    image: postgres:latest
    container_name: udemy_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: udemydb
      POSTGRES_USER: udemyuser
      POSTGRES_PASSWORD: udemypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - udemy_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - udemy.postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - udemy_network

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    restart: always
    volumes:
      - consul_data:/consul/data
    networks:
      - udemy_network

volumes:
  postgres_data:
  pgadmin_data:
  consul_data:

networks:
  udemy_network:
    driver: bridge
