services:
  udemy.auth.api:
    image: ${DOCKER_REGISTRY-}udemyauthapi
    build:
      context: .
      dockerfile: Udemy.Auth/Udemy.Auth.API/Dockerfile
    environment:
      - POSTGRES_HOST=udemy.postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=udemydb
      - POSTGRES_USER=udemyuser
      - POSTGRES_PASSWORD=udemypassword
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.auth.api
      - API_HTTP_PORT=8080
      - API_HTTPS_PORT=8081
      - API_KEY=d0107a8c-b28d-4266-86e5-5ca24a48cc3f # secret api key that should not be known to anyone
      - SALT=123456
    depends_on:
      - udemy.postgres
      - consul
    networks:
      - udemy_network

  udemy.course.api:
    image: ${DOCKER_REGISTRY-}udemycourseapi
    build:
      context: .
      dockerfile: Udemy.Course/Udemy.Course.API/Dockerfile
    environment:
      - POSTGRES_HOST=udemy.postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=udemycoursedb
      - POSTGRES_USER=udemyuser
      - POSTGRES_PASSWORD=udemypassword
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.course.api
      - API_HTTP_PORT=8080
      - API_HTTPS_PORT=8081
      - API_KEY=d0107a8c-b28d-4266-86e5-5ca24a48cc3f # secret api key that should not be known to anyone
      - SALT=123456
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - consul
    networks:
      - udemy_network

  udemy.apigateway.api:
    image: ${DOCKER_REGISTRY-}udemyapigatewayapi
    ports:
      - "5000:8080"
      - "5001:8081"
    build:
      context: .
      dockerfile: Udemy.APIGateway/Udemy.APIGateway.API/Dockerfile
    environment:
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.apigateway.api
      - API_HTTP_PORT=8080
      - API_HTTPS_PORT=8081
      - API_KEY=d0107a8c-b28d-4266-86e5-5ca24a48cc3f # secret api key that should not be known to anyone
      - SALT=123456
    depends_on:
      - consul
      - udemy.auth.api
      - udemy.course.api
      - udemy.cdn.api
    networks:
      - udemy_network

  udemy.cdn.api:
    image: ${DOCKER_REGISTRY-}udemycdnapi
    environment:
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.cdn.api
      - API_HTTP_PORT=8080
      - API_HTTPS_PORT=8081
      - API_KEY=d0107a8c-b28d-4266-86e5-5ca24a48cc3f # secret api key that should not be known to anyone
      - SALT=123456
      - MINIO_URL=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    build:
      context: .
      dockerfile: Udemy.CDN/Udemy.CDN.API/Dockerfile
    depends_on:
      - consul
      - minio
    networks:
      - udemy_network

  udemy.payment.api:
    image: ${DOCKER_REGISTRY-}udemypaymentapi
    environment:
      - CONSUL_URL=http://consul:8500
      - API_HOST=udemy.payment.api
      - API_HTTP_PORT=8080
      - API_HTTPS_PORT=8081
      - API_KEY=d0107a8c-b28d-4266-86e5-5ca24a48cc3f # secret api key that should not be known to anyone
      - SALT=123456
      - RABBITMQ_CONNECTION=amqp://admin:admin123@rabbitmq:5672
    build:
      context: .
      dockerfile: Udemy.Payment/Udemy.Payment.API/Dockerfile
    depends_on:
      - consul
      - rabbitmq
    networks:
      - udemy_network



  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      # - "5672:5672" # AMQP protokolü
      - "15672:15672" # Yönetim konsolu
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  
    networks:
      - udemy_network

  redis:
    image: redis:7.2
    container_name: redis
    # ports:
      # - "6379:6379" # Redis varsayılan portu
    volumes:
      - redis_data:/data
    networks:
      - udemy_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8088:8081"
    environment:
      REDIS_HOSTS: "local:redis:6379"
    volumes:
     - redis_commander_data:/app/data
    networks:
      - udemy_network

  udemy.postgres:
    image: postgres:latest
    container_name: udemy_postgres
    restart: always
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: udemydb
      POSTGRES_USER: udemyuser
      POSTGRES_PASSWORD: udemypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - udemy_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - udemy.postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - udemy_network

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    expose:
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    restart: always
    volumes:
      - consul_data:/consul/data
    networks:
      - udemy_network

  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - udemy_network

  kibana:
    image: kibana:8.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - udemy_network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      # - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - udemy_network

volumes:
  postgres_data:
  pgadmin_data:
  consul_data:
  elasticsearch-data:
  minio_data:
  redis_data:
  redis_commander_data:
  rabbitmq_data:

networks:
  udemy_network:
    driver: bridge



